title: Fibonacci Project Registry (GPT Action)
description: Privacy Policy and Terms
theme: minima
url: https://libardo667.github.io
baseurl: /fib-privacy
markdown: kramdown
plugins: []
kramdown:
  input: GFM
  hard_wrap: false
# GitHub Pages will read this automatically
